import { Node, Edge } from '@xyflow/react';
import { Episode } from './EpisodicMemoryStore';

export type MasteryStatus = 'mastered' | 'learning' | 'locked';

export interface CurriculumNode {
  id: string;
  label: string;
  type: 'domain' | 'topic' | 'subtopic' | 'bridge'; // 'bridge' = auto-generated
  status: MasteryStatus;
  color?: string;
  ringColor?: string;
  prerequisites: string[]; // Node IDs required to unlock this one
  description?: string;
  isAutoGenerated?: boolean; // True if generated by recursive curriculum evolution
  generatedReason?: string;  // Why it was created
}

export interface CurriculumInsert {
  node: CurriculumNode;
  insertBetween: { parent: string; child: string };
  reason: string;
  timestamp: number;
}

export const curriculumNodes: CurriculumNode[] = [
  { id: 'domain-math', type: 'domain', label: 'Mathematics', status: 'mastered', prerequisites: [] },
  
  // Arithmetic
  { id: 'topic-arithmetic', type: 'topic', label: 'Basic Arithmetic', status: 'mastered', color: 'linear-gradient(135deg, #10b981 0%, #047857 100%)', ringColor: '#34d399', prerequisites: ['domain-math'] },
  { id: 'sub-addition', type: 'subtopic', label: 'Addition & Subtraction', status: 'mastered', prerequisites: ['topic-arithmetic'] },
  { id: 'sub-multiplication', type: 'subtopic', label: 'Multiplication & Division', status: 'mastered', prerequisites: ['sub-addition'] },
  
  // Algebra
  { id: 'topic-algebra', type: 'topic', label: 'Algebra', status: 'learning', color: 'linear-gradient(135deg, #8b5cf6 0%, #6d28d9 100%)', ringColor: '#a78bfa', prerequisites: ['sub-multiplication'] },
  { id: 'sub-linear', type: 'subtopic', label: 'Linear Equations', status: 'learning', prerequisites: ['topic-algebra'] },
  { id: 'sub-quadratics', type: 'subtopic', label: 'Quadratics', status: 'locked', prerequisites: ['sub-linear'] },
  
  // Calculus
  { id: 'topic-calculus', type: 'topic', label: 'Calculus', status: 'locked', color: 'linear-gradient(135deg, #f59e0b 0%, #b45309 100%)', ringColor: '#fbbf24', prerequisites: ['sub-quadratics'] },
  { id: 'sub-limits', type: 'subtopic', label: 'Limits', status: 'locked', prerequisites: ['topic-calculus'] },
  { id: 'sub-derivatives', type: 'subtopic', label: 'Derivatives', status: 'locked', prerequisites: ['sub-limits'] },
];

// Helper to deduce edges from prerequisites
export const deriveEdgesFromCurriculum = (nodes: CurriculumNode[]): Edge[] => {
  const edges: Edge[] = [];
  nodes.forEach(node => {
    node.prerequisites.forEach(prereqId => {
       edges.push({
         id: `e-${prereqId}-${node.id}`,
         source: prereqId,
         target: node.id,
       });
    });
  });
  return edges;
};

// Adaptive Sequencing rules
export const evaluateMasteryUnlocks = (currentNodes: CurriculumNode[]): CurriculumNode[] => {
  return currentNodes.map(node => {
    if (node.status === 'locked') {
      const allPrereqsMastered = node.prerequisites.length > 0 && node.prerequisites.every(prereqId => {
        const prereq = currentNodes.find(n => n.id === prereqId);
        return prereq && prereq.status === 'mastered';
      });
      if (allPrereqsMastered) {
        return { ...node, status: 'learning' };
      }
    }
    return node;
  });
};

export const markNodeMastered = (nodes: CurriculumNode[], nodeId: string): CurriculumNode[] => {
  let updated = nodes.map(n => n.id === nodeId ? { ...n, status: 'mastered' as MasteryStatus } : n);
  return evaluateMasteryUnlocks(updated);
};

// ─── Recursive Curriculum Evolution ────────────────────────────────

/**
 * Detect structural gaps in the curriculum by analyzing episode failure patterns.
 * If a concept consistently fails despite multiple strategies, it likely needs
 * a bridge node inserted between it and its parent.
 */
export const detectConceptGaps = (
  nodes: CurriculumNode[],
  episodes: Episode[]
): CurriculumInsert[] => {
  const inserts: CurriculumInsert[] = [];

  // Group episodes by concept
  const conceptEpisodes = new Map<string, Episode[]>();
  for (const ep of episodes) {
    const existing = conceptEpisodes.get(ep.conceptId) || [];
    existing.push(ep);
    conceptEpisodes.set(ep.conceptId, existing);
  }

  for (const [conceptId, eps] of conceptEpisodes) {
    // Only analyze concepts with enough data
    if (eps.length < 3) continue;

    const failureRate = eps.filter(e => e.outcome === 'failure').length / eps.length;
    const avgClarity = eps.reduce((sum, e) => sum + e.clarityScore, 0) / eps.length;

    // High failure rate + low clarity = structural gap
    if (failureRate > 0.6 && avgClarity < 0.4) {
      const node = nodes.find(n => n.id === conceptId);
      if (!node || node.prerequisites.length === 0) continue;

      // Check that we haven't already inserted a bridge for this node
      const existingBridge = nodes.find(n => 
        n.isAutoGenerated && n.prerequisites.includes(node.prerequisites[0]) &&
        node.prerequisites.includes(n.id)
      );
      if (existingBridge) continue;

      const parentId = node.prerequisites[0];
      const bridgeId = `bridge-${conceptId}-${Date.now()}`;
      const bridgeLabel = `Foundations for ${node.label}`;

      inserts.push({
        node: {
          id: bridgeId,
          label: bridgeLabel,
          type: 'bridge',
          status: 'learning',
          prerequisites: [parentId],
          isAutoGenerated: true,
          generatedReason: `Auto-generated: ${(failureRate * 100).toFixed(0)}% failure rate with ${avgClarity.toFixed(2)} avg clarity on "${node.label}". A bridge concept is needed.`,
          color: 'linear-gradient(135deg, #f97316 0%, #ea580c 100%)',
          ringColor: '#fb923c'
        },
        insertBetween: { parent: parentId, child: conceptId },
        reason: `${(failureRate * 100).toFixed(0)}% failure rate on "${node.label}" — inserting prerequisite bridge`,
        timestamp: Date.now()
      });
    }
  }

  return inserts;
};

/**
 * Apply curriculum inserts — modifies the node graph by inserting bridge nodes
 * and rewiring prerequisites. Fully autonomous — the system IS the teacher.
 */
export const applyCurriculumInserts = (
  nodes: CurriculumNode[],
  inserts: CurriculumInsert[]
): CurriculumNode[] => {
  let updated = [...nodes];

  for (const insert of inserts) {
    // Add the bridge node
    updated.push(insert.node);

    // Rewire: the child's prerequisite changes from parent to bridge
    updated = updated.map(n => {
      if (n.id === insert.insertBetween.child) {
        return {
          ...n,
          prerequisites: n.prerequisites.map(p =>
            p === insert.insertBetween.parent ? insert.node.id : p
          )
        };
      }
      return n;
    });
  }

  return evaluateMasteryUnlocks(updated);
};

/**
 * Detect implicit cross-links: if students consistently need concepts from
 * unrelated branches to understand a topic, create a cross-prerequisite.
 */
export const detectCrossLinks = (
  nodes: CurriculumNode[],
  episodes: Episode[]
): { sourceId: string; targetId: string; reason: string }[] => {
  const crossLinks: { sourceId: string; targetId: string; reason: string }[] = [];

  // Find concepts where success correlates with mastery of unrelated concepts
  const conceptEpisodes = new Map<string, Episode[]>();
  for (const ep of episodes) {
    const existing = conceptEpisodes.get(ep.conceptId) || [];
    existing.push(ep);
    conceptEpisodes.set(ep.conceptId, existing);
  }

  // For each struggling concept, check if success only happened after another concept was mastered
  for (const [conceptId, eps] of conceptEpisodes) {
    if (eps.length < 4) continue;

    const node = nodes.find(n => n.id === conceptId);
    if (!node) continue;

    // Find concepts that the student was also working on during success episodes
    const successEps = eps.filter(e => e.outcome === 'success');
    const failureEps = eps.filter(e => e.outcome === 'failure');

    if (successEps.length === 0 || failureEps.length < 2) continue;

    // If all success episodes came AFTER failures, and another concept was being studied between,
    // it might be an implicit prerequisite. This is a simplified heuristic.
    const firstSuccess = successEps[successEps.length - 1]; // Oldest success
    const otherConceptsStudied = episodes
      .filter(e => e.conceptId !== conceptId && e.timestamp < firstSuccess.timestamp && e.outcome === 'success')
      .map(e => e.conceptId);

    for (const otherConceptId of new Set(otherConceptsStudied)) {
      // Check it's not already a prerequisite
      if (!node.prerequisites.includes(otherConceptId)) {
        crossLinks.push({
          sourceId: otherConceptId,
          targetId: conceptId,
          reason: `Student succeeded on "${node.label}" only after mastering concepts in "${otherConceptId}" branch`
        });
      }
    }
  }

  return crossLinks.slice(0, 3); // Limit to top 3 to avoid graph explosion
};
